### ISSUE TITLE
Depth Fusion

### ISSUE THREAD

**Issue by Dumeowmeow** [lingxiao-li/Bifrost#4]
Thank you for your great work!
May I ask how to do the Depth Fusion part in Figure2?

**Comment by lingxiao-li** [comment]
The pseudo-code for depth fusion is looks like this

<img width="701" alt="Screenshot 2024-11-04 at 20 24 16" src="https://github.com/user-attachments/assets/d3b33c76-4375-4ff6-b4df-46cf631d2d1d">
